//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubbyBook.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.AuthorRates = new HashSet<AuthorRate>();
            this.BookAuthors = new HashSet<BookAuthor>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<int> BirthdayYear { get; set; }
        public Nullable<int> DeathYear { get; set; }
        public string ShortDescription { get; set; }
        public string Biography { get; set; }
        public string PhotoPath { get; set; }
        public string UrlRewrite { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public sbyte sbType { get; set; }
        public sbyte sbGender { get; set; }
    
        public virtual ICollection<AuthorRate> AuthorRates { get; set; }
        public virtual ICollection<BookAuthor> BookAuthors { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
