//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubbyBook.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BookAuthors = new HashSet<BookAuthor>();
            this.BookGenres = new HashSet<BookGenre>();
            this.BookRates = new HashSet<BookRate>();
            this.UserBooks = new HashSet<UserBook>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string OriginalTitle { get; set; }
        public string Description { get; set; }
        public string CoverPath { get; set; }
        public string UrlRewrite { get; set; }
        public bool Confirmed { get; set; }
        public bool Collection { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        public virtual ICollection<BookAuthor> BookAuthors { get; set; }
        public virtual ICollection<BookGenre> BookGenres { get; set; }
        public virtual ICollection<BookRate> BookRates { get; set; }
        public virtual ICollection<UserBook> UserBooks { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
