//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubbyBook.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int Id { get; set; }
        public int CountryId { get; set; }
        public int DistrictId { get; set; }
        public string Name { get; set; }
        public string UrlRewrite { get; set; }
        public bool Default { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual District District { get; set; }
    }
}
