//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubbyBook.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public Genre()
        {
            this.BookGenres = new HashSet<BookGenre>();
            this.Children = new HashSet<Genre>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string UrlRewrite { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int Order { get; set; }
    
        public virtual ICollection<BookGenre> BookGenres { get; set; }
        public virtual ICollection<Genre> Children { get; set; }
        public virtual Genre Parent { get; set; }
    }
}
