//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubbyBook.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Nickname { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<sbyte> sbGender { get; set; }
        public Nullable<int> CityId { get; set; }
        public string ImagePath { get; set; }
        public string UrlRewrite { get; set; }
    
        public virtual City City { get; set; }
        public virtual User User { get; set; }
    }
}
