//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubbyBook.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemNotification
    {
        public int Id { get; set; }
        public int NotificationId { get; set; }
        public sbyte sbType { get; set; }
        public bool IsNew { get; set; }
        public int OwnerUserId { get; set; }
    
        public virtual Notification Notification { get; set; }
        public virtual User User { get; set; }
    }
}
